"""added createdAt field to rate customzations table

Revision ID: 1d814dd82938
Revises: 2b3874fddee0
Create Date: 2025-10-15 21:00:11.129602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d814dd82938'
down_revision: Union[str, Sequence[str], None] = '2b3874fddee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_customizations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate_customizations', 'created_at')
    # ### end Alembic commands ###
