"""ficed gemoerty name

Revision ID: 1eb993c8e081
Revises: abfcca355c1e
Create Date: 2025-11-03 19:48:37.724165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb993c8e081'
down_revision: Union[str, Sequence[str], None] = 'abfcca355c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('geometry_encrypted', sa.Text(), nullable=True))
    op.drop_column('trips', 'geometry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('geometry', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('trips', 'geometry_encrypted')
    # ### end Alembic commands ###
