"""Add audit trail table

Revision ID: 1f182aaf695f
Revises: 740a3b1742ae
Create Date: 2025-12-01 14:44:21.589826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f182aaf695f'
down_revision: Union[str, Sequence[str], None] = '740a3b1742ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('REPORT_REQUESTED', 'REPORT_GENERATED', 'REPORT_FAILED', 'REPORT_DOWNLOADED', 'RATE_CUSTOMIZATION_CREATED', 'RATE_CUSTOMIZATION_UPDATED', 'RATE_CUSTOMIZATION_DELETED', 'RATE_CATEGORY_CREATED', 'RATE_CATEGORY_UPDATED', 'RATE_CATEGORY_DELETED', name='audit_action'), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_trails_action'), 'audit_trails', ['action'], unique=False)
    op.create_index(op.f('ix_audit_trails_id'), 'audit_trails', ['id'], unique=False)
    op.create_index(op.f('ix_audit_trails_resource'), 'audit_trails', ['resource'], unique=False)
    op.create_index(op.f('ix_audit_trails_resource_id'), 'audit_trails', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_trails_timestamp'), 'audit_trails', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_trails_timestamp'), table_name='audit_trails')
    op.drop_index(op.f('ix_audit_trails_resource_id'), table_name='audit_trails')
    op.drop_index(op.f('ix_audit_trails_resource'), table_name='audit_trails')
    op.drop_index(op.f('ix_audit_trails_id'), table_name='audit_trails')
    op.drop_index(op.f('ix_audit_trails_action'), table_name='audit_trails')
    op.drop_table('audit_trails')
    # ### end Alembic commands ###
