"""Added retry count

Revision ID: 27505d66ecb0
Revises: 4276e0ee343b
Create Date: 2025-11-25 18:55:28.612934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27505d66ecb0'
down_revision: Union[str, Sequence[str], None] = '4276e0ee343b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('retry_attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'retry_attempts')
    # ### end Alembic commands ###
