"""added rateCustomizations table and relation to trips

Revision ID: 2b3874fddee0
Revises: 2d7958bd5443
Create Date: 2025-10-15 19:57:01.873404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3874fddee0'
down_revision: Union[str, Sequence[str], None] = '2d7958bd5443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_customizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_customizations_id'), 'rate_customizations', ['id'], unique=False)
    op.add_column('trips', sa.Column('rate_customization_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'trips', 'rate_customizations', ['rate_customization_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'rate_customization_id')
    op.drop_index(op.f('ix_rate_customizations_id'), table_name='rate_customizations')
    op.drop_table('rate_customizations')
    # ### end Alembic commands ###
