"""add reimbursement types and fix updated at

Revision ID: 334c63896792
Revises: 63571b1ccd92
Create Date: 2025-10-20 16:38:57.225216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334c63896792'
down_revision: Union[str, Sequence[str], None] = '63571b1ccd92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('mileage_reimbursement_total', sa.DOUBLE_PRECISION(), nullable=True))
    op.add_column('trips', sa.Column('expense_reimbursement_total', sa.DOUBLE_PRECISION(), nullable=True))
    op.drop_column('trips', 'reimbursement_total')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('reimbursement_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('trips', 'expense_reimbursement_total')
    op.drop_column('trips', 'mileage_reimbursement_total')
    # ### end Alembic commands ###
