"""Creating CommonPlaces table

Revision ID: 3b448e459963
Revises: 8a14f3e7fef4
Create Date: 2025-11-28 09:24:17.403489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b448e459963'
down_revision: Union[str, Sequence[str], None] = '8a14f3e7fef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_places',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_common_places_customization_name')
    )
    op.create_index(op.f('ix_common_places_id'), 'common_places', ['id'], unique=False)
    op.create_index(op.f('ix_common_places_user_id'), 'common_places', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_common_places_user_id'), table_name='common_places')
    op.drop_index(op.f('ix_common_places_id'), table_name='common_places')
    op.drop_table('common_places')
    # ### end Alembic commands ###
