"""Added new enum field expired

Revision ID: 4276e0ee343b
Revises: d9bf867a967c
Create Date: 2025-11-25 17:27:38.062283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4276e0ee343b'
down_revision: Union[str, Sequence[str], None] = 'd9bf867a967c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Name of the enum type in DB
ENUM_NAME = "report_status"
NEW_VALUE = "expired"
OLD_VALUE = "expired"  # needed for downgrade rewrite

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new enum value only if it doesn't exist
    conn = op.get_bind()

    # Check if value already exists (avoid errors if applied twice)
    exists = conn.execute(
        sa.text(f"SELECT 1 FROM pg_enum e JOIN pg_type t ON e.enumtypid = t.oid WHERE t.typname = :name AND e.enumlabel = :value"),
        {"name": ENUM_NAME, "value": NEW_VALUE}
    ).fetchone()

    if not exists:
        op.execute(sa.text(f"ALTER TYPE {ENUM_NAME} ADD VALUE '{NEW_VALUE}';"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # Create new enum without the expired value
    op.execute("ALTER TYPE report_status RENAME TO report_status_old;")

    op.execute("""
        CREATE TYPE report_status AS ENUM ('pending','processing','completed','failed');
    """)

    # Update columns using cast
    op.execute("""
        ALTER TABLE reports 
        ALTER COLUMN status 
        TYPE report_status 
        USING status::text::report_status;
    """)

    # Drop old enum
    op.execute("DROP TYPE report_status_old;")
    # ### end Alembic commands ###
