"""add reimbursement_total to trips

Revision ID: 63571b1ccd92
Revises: 8594a259bbfc
Create Date: 2025-10-20 16:28:43.138394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63571b1ccd92'
down_revision: Union[str, Sequence[str], None] = '8594a259bbfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('reimbursement_total', sa.DOUBLE_PRECISION(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'reimbursement_total')
    # ### end Alembic commands ###
