"""Add processing_started_at to reports

Revision ID: 66f7043d9927
Revises: 27505d66ecb0
Create Date: 2025-11-30 13:55:02.858143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f7043d9927'
down_revision: Union[str, Sequence[str], None] = '27505d66ecb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'processing_started_at')
    # ### end Alembic commands ###
