"""Add processing_started_at and remove storage_key from reports

Revision ID: 6d5f243e9943
Revises: 66f7043d9927
Create Date: 2025-11-30 14:04:15.870187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5f243e9943'
down_revision: Union[str, Sequence[str], None] = '66f7043d9927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'storage_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('storage_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
