"""created_Trips_table

Revision ID: 6f7f395feab9
Revises: 
Create Date: 2025-10-11 19:31:35.611625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7f395feab9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='trip_status'), nullable=False),
    sa.Column('start_address_encrypted', sa.String(length=128), nullable=False),
    sa.Column('end_address_encrypted', sa.String(length=128), nullable=True),
    sa.Column('category', sa.Enum('business', 'personal', name='trip_category'), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('reimbursement_rate', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
