"""added constraints

Revision ID: 7fe8eefc70ca
Revises: 334c63896792
Create Date: 2025-10-22 12:07:45.513880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe8eefc70ca'
down_revision: Union[str, Sequence[str], None] = '334c63896792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_expenses_trip_id_type', 'expenses', ['trip_id', 'type'])
    op.create_unique_constraint('uq_rate_categories_customization_name', 'rate_categories', ['rate_customization_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_rate_categories_customization_name', 'rate_categories', type_='unique')
    op.drop_constraint('uq_expenses_trip_id_type', 'expenses', type_='unique')
    # ### end Alembic commands ###
