"""add miles field to trips

Revision ID: 8594a259bbfc
Revises: 47a2dc110226
Create Date: 2025-10-20 16:25:02.243446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8594a259bbfc'
down_revision: Union[str, Sequence[str], None] = '47a2dc110226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('miles', sa.DOUBLE_PRECISION(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'miles')
    # ### end Alembic commands ###
