"""fixed name

Revision ID: 8a48a9788c79
Revises: 7fe8eefc70ca
Create Date: 2025-10-26 17:24:29.372668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a48a9788c79'
down_revision: Union[str, Sequence[str], None] = '7fe8eefc70ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('amount', sa.DOUBLE_PRECISION(), nullable=False))
    op.drop_column('expenses', 'amount_cents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('amount_cents', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('expenses', 'amount')
    # ### end Alembic commands ###
