"""add_vehicles_table_and_update_trips_vehicle_reference

Revision ID: 9323bd43ca49
Revises: 740a3b1742ae
Create Date: 2025-12-22 11:02:20.921517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9323bd43ca49'
down_revision: Union[str, Sequence[str], None] = '740a3b1742ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'license_plate', name='uq_vehicles_user_license_plate'),
    sa.UniqueConstraint('user_id', 'name', name='uq_vehicles_user_name')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.add_column('trips', sa.Column('vehicle_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'trips', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    op.drop_column('trips', 'vehicle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('vehicle', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_column('trips', 'vehicle_id')
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
