"""add user relationships to all tables

Revision ID: 944064892c74
Revises: 82544dc02477
Create Date: 2025-11-13 23:40:37.359451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944064892c74'
down_revision: Union[str, Sequence[str], None] = '82544dc02477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('rate_customizations', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_rate_customizations_user_id'), 'rate_customizations', ['user_id'], unique=False)
    op.create_unique_constraint('uq_rate_customizations_user_name', 'rate_customizations', ['user_id', 'name'])
    op.create_foreign_key(None, 'rate_customizations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('trips', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_foreign_key(None, 'trips', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_column('trips', 'user_id')
    op.drop_constraint(None, 'rate_customizations', type_='foreignkey')
    op.drop_constraint('uq_rate_customizations_user_name', 'rate_customizations', type_='unique')
    op.drop_index(op.f('ix_rate_customizations_user_id'), table_name='rate_customizations')
    op.drop_column('rate_customizations', 'user_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_column('expenses', 'user_id')
    # ### end Alembic commands ###
