"""add_vehicle_field_to_trips

Revision ID: 9e1d0d1b78c5
Revises: 6e54ed232b7d
Create Date: 2025-11-13 18:35:22.978073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1d0d1b78c5'
down_revision: Union[str, Sequence[str], None] = '6e54ed232b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('vehicle', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'vehicle')
    # ### end Alembic commands ###
