"""added gemorety field

Revision ID: abfcca355c1e
Revises: 8a48a9788c79
Create Date: 2025-10-29 20:04:08.417815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abfcca355c1e'
down_revision: Union[str, Sequence[str], None] = '8a48a9788c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('geometry', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'geometry')
    # ### end Alembic commands ###
