"""Fix Audit Actions

Revision ID: c95603f355b1
Revises: 1f182aaf695f
Create Date: 2026-01-06 12:11:04.754365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95603f355b1'
down_revision: Union[str, Sequence[str], None] = '1f182aaf695f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_trails_user_id'), 'audit_trails', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_trails_user_id'), table_name='audit_trails')
    # ### end Alembic commands ###
