"""drop trip_category

Revision ID: d80ec73818d7
Revises: fda54d221da2
Create Date: 2025-10-20 12:38:21.820913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd80ec73818d7'
down_revision: Union[str, Sequence[str], None] = 'fda54d221da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('category', postgresql.ENUM('business', 'personal', name='trip_category'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
