"""Added storage key and expires at field for reports

Revision ID: d9bf867a967c
Revises: 6c643ac24de6
Create Date: 2025-11-24 12:58:53.848890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bf867a967c'
down_revision: Union[str, Sequence[str], None] = '6c643ac24de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('storage_key', sa.String(length=255), nullable=True))
    op.add_column('reports', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'expires_at')
    op.drop_column('reports', 'storage_key')
    # ### end Alembic commands ###
