"""add rate customization, category, and trip relationships

Revision ID: fda54d221da2
Revises: 1d814dd82938
Create Date: 2025-10-18 11:37:02.160132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda54d221da2'
down_revision: Union[str, Sequence[str], None] = '1d814dd82938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('cost_per_mile', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rate_customization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rate_customization_id'], ['rate_customizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_categories_id'), 'rate_categories', ['id'], unique=False)
    op.add_column('trips', sa.Column('rate_category_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'trips', 'rate_categories', ['rate_category_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'rate_category_id')
    op.drop_index(op.f('ix_rate_categories_id'), table_name='rate_categories')
    op.drop_table('rate_categories')
    # ### end Alembic commands ###
